[project]
user_env = []
session_timeout = 3600
user_session_timeout = 1296000
cache = false
persist_user_env = false
mask_user_env = false
allow_origins = ["*"]

[features]
# Allow markdown formatting & buttons
unsafe_allow_html = true
latex = true
user_message_autoscroll = true
auto_tag_thread = true
edit_message = true
allow_thread_sharing = false

[features.spontaneous_file_upload]
enabled = true
accept = ["*/*"]
max_files = 20
max_size_mb = 500

[features.audio]
enabled = false
sample_rate = 24000
[UI]
# Bot name
name = "IRC Bot"

# UI preferences
default_theme = "dark"
layout = "wide"
default_sidebar_state = "open"
cot = "tool_call"
hide_readme = true

# ✅ Use local NHAI logo
logo_file_url = "/public/nhai_logo.png"
default_avatar_file_url = "/public/nhai_logo.png"

# 🏠 Home button with NHAI icon
[[UI.header_links]]
name = "Home"
display_name = "Home"
icon_url = "/public/nhai_logo.png"
url = "https://nh-ai.org"
target = "_blank"


# ✅ Optional: Custom CSS for more control over UI
# custom_css = "/public/styles.css"

# ✅ Optional: Custom JS if you want to add animations or analytics
# custom_js = "/public/custom.js"

[meta]
generated_by = "2.8.3"
